tokenfactory:
  issuer: http://localhost:8080
  json-keyset: classpath:json-keys.json
  default-key-id: ec-1
  
  clients:
    - username: tokenfactory
      password: tokenfactory


spring: 
  jackson:
    default-property-inclusion: non-null
    property-naming-strategy: SNAKE_CASE
  